server:
  port: 5001
  servlet:
    context-path: /data_base-app
spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
    database: postgresql
  sql:
    init:
      data-locations: classpath*:data.sql
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/AirLines
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
