server:
  port: 5001
  servlet:
    context-path: /data_base-app
spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:airlinedb
    driver-class-name: org.h2.Driver
    username: sasha
    password: sasha
  sql:
    init:
      mode: always
