server:
  port: 5002
  servlet:
    context-path: /web-app
spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
    database: postgresql
  sql:
    init:
      data-locations: classpath*:security.sql
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/SecurUser
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

